# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8916531b5edeb222b923c0c04b411a9403e006a4340cc1bee0e1f5eaf2d6339532fb035898d1526c705027c4622638d037e10d53c4869d5fe05eb39f96dd2f

test:
  secret_key_base: 566615577ed8b940b41d480af40f33489d1bcd115dc83911ba9b384dc01415a6bc0862e244a56503e087b8bf82738c91c5d1c225fa09fff7281b5cbb72d3bfd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
